# ====================================================
# CONFIGURACIÓN PRINCIPAL DEL JUPYTER BOOK
# ====================================================

title: "Series de Tiempo 2025 - Grupo 9"
author: "Sandra Guzmán y Grupo 9"

# ====================================================
# CONTROL DE EJECUCIÓN DE NOTEBOOKS
# ====================================================
execute:
  execute_notebooks: "off"

# ====================================================
# ESTRUCTURA Y RUTAS
# ====================================================
only_build_toc_files: true

# ====================================================
# REPOSITORIO (IMPORTANTE para desplegar)
# ====================================================
repository:
  url: https://github.com/Sandra-guzman/Series-de-tiempo-2025-grupo-9
  branch: main
  path_to_book: book

# ====================================================
# OPCIONES DE HTML
# ====================================================
html:
  favicon: ""
  logo: ""
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false

