# ===========================================
# CONFIGURACIÓN DEL JUPYTER BOOK
# ===========================================

title: "Series de tiempo 2025 - Grupo 9"
author: "Sandra Guzmán"
logo: null
only_build_toc_files: true

execute:
  execute_notebooks: "off"

html:
  favicon: null
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  home_page_in_navbar: true
